Index: ChangeLog from  Nicolas Burrus  <burrus_n@lrde.epita.fr>         * contrib/runtests: Check if the current test is present. Fix         the TESTS variable handling.
Index: olena/ChangeLog
from  Nicolas Burrus  <burrus_n@lrde.epita.fr>
        * tests/morpho/tests/test-reconstruction(main): Use rdata.

Index: integre/ChangeLog
from  Nicolas Burrus  <burrus_n@lrde.epita.fr>
        * tests/types/runtests: Handle the TESTS variable.

    prcs2git-id: 2003paradigm.87

diff --git a/contrib/runtests b/contrib/runtests
--- a/contrib/runtests
+++ b/contrib/runtests
@@ -18,7 +18,7 @@ indir=${SRCDIR-.}/tests
 rundir=runs
 test -d $rundir || mkdir $rundir
 
-if test ${TESTS+set}; then
+if test "$# = 0 -a ${TESTS+set}"; then
   set $TESTS
 fi
 
@@ -29,13 +29,17 @@ if test $# = 0; then
 fi
 
 for test; do
-  # We want only the basename of $test.
   if test -d $test; then continue; fi
   echo $test | grep '~$' && continue;
+  # We want only the basename of $test.
   test=`basename "$test"`
   fail=0
   dir=$rundir/$test
   input=$indir/$test
+  test -f $input || { 
+    echo "FAIL: $test (does not exist)" >&2
+    failures=`expr $failures + 1`
+    continue; }
   rm -rf $dir
   mkdir $dir
   # Build the source code to compile.
diff --git a/integre/tests/types/runtests b/integre/tests/types/runtests
--- a/integre/tests/types/runtests
+++ b/integre/tests/types/runtests
@@ -18,6 +18,10 @@ indir=${SRCDIR-.}/tests
 rundir=runs
 test -d $rundir || mkdir $rundir
 
+if test "$# = 0 -a ${TESTS+set}"; then
+  set $TESTS
+fi
+
 # If no tests were given on the command line, get the list from $indir.
 if test $# = 0; then
   set dummy $indir/*
@@ -32,6 +36,10 @@ for test; do
   fail=0
   dir=$rundir/$test
   input=$indir/$test
+  test -f $input || { 
+    echo "FAIL: $test (does not exist)" >&2
+    failures=`expr $failures + 1`
+    continue; }
   rm -rf $dir
   mkdir $dir
   # Build the source code to compile.
@@ -84,7 +92,11 @@ EOF
 
   msg="";
   case $expected:$estatus in
-    ok:0 | compfail:50 | abort:134) rm -rf "$dir" ;;
+    ok:0 | compfail:50 | abort:134) 
+      if test ! x"$KEEP_RUN" = x"1"; then
+        rm -rf "$dir";
+      fi
+      msg="(ok)" ;;
     *:50) msg="(doesn't compile)" ;;
     *:134) msg="(aborts at run-time)" ;;
     compfail:*) msg="(compiles!)" ;;
@@ -92,7 +104,7 @@ EOF
     ok:*) msg="(exits with \$?=$estatus)" ;;
     *) ;;
   esac
-  if test -d $dir; then
+  if test x"$msg" != x"(ok)"; then
     if test "$xfail" = "no"; then
       echo "FAIL: $test $msg" >&2
       failures=`expr $failures + 1`
