Index: ChangeLog from  +2003-02-12  Raphaël Poss  <raph@lrde.epita.fr>
   (Changes from 0.7)

   * configure.ac: More verbose help. Better version support. Allow
   disabling manpages regeneration.

Index: oln/ChangeLog
from  +2003-02-11  Raphaël Poss  <raph@lrde.epita.fr>

   (Changes from 0.7)

   * oln/Makefile.am: Remove file.

   * config/oln.m4 (OLN_VERSION, OLN_MAJOR_VERSION): Put under
   version control.

   * conf/oln-config.shin (Usage): Minor fixes.

Index: doc/ChangeLog
from  +2003-02-12  Raphaël Poss  <raph@lrde.epita.fr>

   (Changes from 0.7)

   * dev/oln-dev.texi: Tweak copyright holder name.

   * ref/Makefile.am (docdir): Minor fix.
   * dev/Makefile.am (docdir): Minor fix.

   * ref/oln-ref.tex: Update.

Index: tools/ChangeLog
from  +2003-02-12  Raphaël Poss  <raph@lrde.epita.fr>

   (Changes from 0.7)

   * utilities/Makefile.am: Auto-generate manpages. Fix small
   dependency problem.
   * utilities/morpho/Makefile.am: Likewise.

   * utilities/morpho/generate_morpho.sh: Add copyright information.

   * utilities/mosaic.cc: Add copyright information. Modify to use
   with help2man.
   * utilities/morpho/morpho_template.cc,
   utilities/morpho/morpho_template_extrema.cc,
   utilities/morpho/morpho_template_gaussian.cc,
   utilities/morpho/morpho_template_watershed.cc,
   utilities/morpho/morpho_template_with_twowin.cc,
   utilities/morpho/morpho_template_with_neighb.cc,
   utilities/morpho/morpho_template_with_functor.cc: Likewise.

    prcs2git-id: 8.3

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -7,15 +7,6 @@ SUBDIRS = oln $(OLN_TOP_SUBDIRS)
 ACLOCAL_AMFLAGS = -I oln/config
 CONFIGURE_DEPENDENCIES = oln/config/oln.m4
 
-# This is totally experimental. Comments are welcome.
-maintainer-check:
-	if cppi --version >/dev/null 2>&1; then \
-	  find $(srcdir) -name '*.{cc,hh,hxx}' | \
-	    xargs cppi --check; \
-	else \
-	  echo "$@: GNU cppi is required" >&2; \
-	fi
-
 dist_noinst_DATA = README BUILD INSTALL THANKS FAQ
 MAINTAINERCLEANFILES = README BUILD INSTALL THANKS FAQ
 
@@ -37,3 +28,15 @@ THANKS:
 
 FAQ: 
 	$(INFOTOTEXT) $(devdoc)/faq.texi >$@
+
+DISTCHECK_CONFIGURE_FLAGS = --disable-manpages-regen
+
+# This is totally experimental. Comments are welcome.
+maintainer-check:
+	if cppi --version >/dev/null 2>&1; then \
+	  find $(srcdir) -name '*.{cc,hh,hxx}' | \
+	    xargs cppi --check; \
+	else \
+	  echo "$@: GNU cppi is required" >&2; \
+	fi
+
