2002-03-28  Alexandre Duret-Lutz  <duret_g@epita.fr>
	* tests/: New directory.  See tests/ChangeLog.
	* Makefile.am (SUBDIRS): Add tests.
	* configure.ac: Run AC_PROG_RANLIB.
	Output tests/Makefile, tests/check/Makefile, tests/io/Makefile,
	tests/morpho/Makefile.
	* demo/test-reconstruction.cc: Remove most of the testing code,
	which is now in tests/morpho/.

2002-03-28  Alexandre Duret-Lutz  <duret_g@epita.fr>

	* tests/ChangeLog, tests/morpho/Makefile.am,
	tests/morpho/Makefile.in, tests/morpho/reconstruction.cc,
	tests/check/srcdir.hh, tests/check/Makefile.flags,
	tests/check/Makefile.check, tests/check/srcdir.cc,
	tests/check/Makefile.in, tests/check/check.hh,
	tests/check/verbose.cc, tests/check/verbose.hh,
	tests/check/main.cc, tests/check/Makefile.am, tests/Makefile.am,
	tests/Makefile.in, tests/io/loadsave.hh, tests/io/Makefile.am,
	tests/io/Makefile.in, tests/data/lena.ppm: New files.

    prcs2git-id: 0_3.18

diff --git a/tests/io/Makefile.in b/tests/io/Makefile.in
--- a/tests/io/Makefile.in
+++ b/tests/io/Makefile.in
@@ -13,6 +13,10 @@
 # PARTICULAR PURPOSE.
 
 @SET_MAKE@
+
+# -*- Makefile -*-
+
+# -*- Makefile -*-
 SHELL = @SHELL@
 
 srcdir = @srcdir@
@@ -36,7 +40,7 @@ oldincludedir = /usr/include
 pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
-top_builddir = ..
+top_builddir = ../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -75,34 +79,25 @@ am__include = @am__include@
 am__quote = @am__quote@
 install_sh = @install_sh@
 
-INCLUDES = -I$(top_srcdir)/src
-AM_CXXFLAGS = -Wall -W -DNDEBUG -ftemplate-depth-50 -ansi -pedantic
-noinst_PROGRAMS = tour morpholena test-reconstruction
-tour_SOURCES = tour.cc
-morpholena_SOURCES = morpholena.cc
-test_reconstruction_SOURCES = test-reconstruction.cc
-subdir = demo
+AM_CXXFLAGS = -Wall -W -ftemplate-depth-50 -ansi -pedantic
+AM_CPPFLAGS = -I$(top_srcdir)/src -I$(top_srcdir)/tests/check
+
+# Automake 1.6 complains about AM_LDADD.  See PR automake/311.
+LDADD = ../check/libcheck.a
+
+check_PROGRAMS = 2d
+2d_SOURCES = 2d.cc loadsave.hh
+
+TESTS = 2d
+subdir = tests/io
 mkinstalldirs = $(SHELL) $(top_srcdir)/tools/mkinstalldirs
 CONFIG_CLEAN_FILES =
-noinst_PROGRAMS = tour$(EXEEXT) morpholena$(EXEEXT) \
-	test-reconstruction$(EXEEXT)
-PROGRAMS = $(noinst_PROGRAMS)
-
-am_morpholena_OBJECTS = morpholena.$(OBJEXT)
-morpholena_OBJECTS = $(am_morpholena_OBJECTS)
-morpholena_LDADD = $(LDADD)
-morpholena_DEPENDENCIES =
-morpholena_LDFLAGS =
-am_test_reconstruction_OBJECTS = test-reconstruction.$(OBJEXT)
-test_reconstruction_OBJECTS = $(am_test_reconstruction_OBJECTS)
-test_reconstruction_LDADD = $(LDADD)
-test_reconstruction_DEPENDENCIES =
-test_reconstruction_LDFLAGS =
-am_tour_OBJECTS = tour.$(OBJEXT)
-tour_OBJECTS = $(am_tour_OBJECTS)
-tour_LDADD = $(LDADD)
-tour_DEPENDENCIES =
-tour_LDFLAGS =
+check_PROGRAMS = 2d$(EXEEXT)
+am_2d_OBJECTS = 2d.$(OBJEXT)
+2d_OBJECTS = $(am_2d_OBJECTS)
+2d_LDADD = $(LDADD)
+2d_DEPENDENCIES = ../check/libcheck.a
+2d_LDFLAGS =
 
 DEFS = @DEFS@
 DEFAULT_INCLUDES =  -I. -I$(srcdir)
@@ -111,41 +106,37 @@ LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
 depcomp = $(SHELL) $(top_srcdir)/tools/depcomp
 am__depfiles_maybe = depfiles
-@AMDEP_TRUE@DEP_FILES = ./$(DEPDIR)/morpholena.Po \
-@AMDEP_TRUE@	./$(DEPDIR)/test-reconstruction.Po \
-@AMDEP_TRUE@	./$(DEPDIR)/tour.Po
+@AMDEP_TRUE@DEP_FILES = ./$(DEPDIR)/2d.Po
 CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
 	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
 CXXLD = $(CXX)
 CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
 	-o $@
 CXXFLAGS = @CXXFLAGS@
-DIST_SOURCES = $(morpholena_SOURCES) $(test_reconstruction_SOURCES) \
-	$(tour_SOURCES)
+CFLAGS = @CFLAGS@
+COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
+	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
+CCLD = $(CC)
+LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
+DIST_SOURCES = $(2d_SOURCES)
 DIST_COMMON = Makefile.am Makefile.in
-SOURCES = $(morpholena_SOURCES) $(test_reconstruction_SOURCES) $(tour_SOURCES)
+SOURCES = $(2d_SOURCES)
 
 all: all-am
 
 .SUFFIXES:
 .SUFFIXES: .cc .o .obj
-$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
+$(srcdir)/Makefile.in:  Makefile.am $(top_srcdir)/tests/check/Makefile.check $(top_srcdir)/tests/check/Makefile.flags $(top_srcdir)/configure.ac $(ACLOCAL_M4)
 	cd $(top_srcdir) && \
-	  $(AUTOMAKE) --gnu  demo/Makefile
+	  $(AUTOMAKE) --gnu  tests/io/Makefile
 Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
-morpholena$(EXEEXT): $(morpholena_OBJECTS) $(morpholena_DEPENDENCIES) 
-	@rm -f morpholena$(EXEEXT)
-	$(CXXLINK) $(morpholena_LDFLAGS) $(morpholena_OBJECTS) $(morpholena_LDADD) $(LIBS)
-test-reconstruction$(EXEEXT): $(test_reconstruction_OBJECTS) $(test_reconstruction_DEPENDENCIES) 
-	@rm -f test-reconstruction$(EXEEXT)
-	$(CXXLINK) $(test_reconstruction_LDFLAGS) $(test_reconstruction_OBJECTS) $(test_reconstruction_LDADD) $(LIBS)
-tour$(EXEEXT): $(tour_OBJECTS) $(tour_DEPENDENCIES) 
-	@rm -f tour$(EXEEXT)
-	$(CXXLINK) $(tour_LDFLAGS) $(tour_OBJECTS) $(tour_LDADD) $(LIBS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
+2d$(EXEEXT): $(2d_OBJECTS) $(2d_DEPENDENCIES) 
+	@rm -f 2d$(EXEEXT)
+	$(CXXLINK) $(2d_LDFLAGS) $(2d_OBJECTS) $(2d_LDADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT) core *.core
@@ -153,9 +144,7 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/morpholena.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/test-reconstruction.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/tour.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/2d.Po@am__quote@
 
 distclean-depend:
 	-rm -rf ./$(DEPDIR)
@@ -209,9 +198,64 @@ GTAGS:
 
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH
+
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+	        xpass=`expr $$xpass + 1`; \
+	        failed=`expr $$failed + 1`; \
+	        echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+	        echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+	        xfail=`expr $$xfail + 1`; \
+	        echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+	        failed=`expr $$failed + 1`; \
+	        echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes=`echo "$$banner" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 
-top_distdir = ..
+top_distdir = ../..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
@@ -234,8 +278,10 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
-all-am: Makefile $(PROGRAMS)
+all-am: Makefile
 
 installdirs:
 
@@ -265,7 +311,7 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-generic clean-noinstPROGRAMS mostlyclean-am
+clean-am: clean-checkPROGRAMS clean-generic mostlyclean-am
 
 distclean: distclean-am
 
@@ -300,8 +346,8 @@ mostlyclean-am: mostlyclean-compile mostlyclean-generic
 
 uninstall-am: uninstall-info-am
 
-.PHONY: GTAGS all all-am check check-am clean clean-generic \
-	clean-noinstPROGRAMS distclean distclean-compile \
+.PHONY: GTAGS all all-am check check-TESTS check-am clean \
+	clean-checkPROGRAMS clean-generic distclean distclean-compile \
 	distclean-depend distclean-generic distclean-tags distdir dvi \
 	dvi-am info info-am install install-am install-data \
 	install-data-am install-exec install-exec-am install-info \
