2002-06-05  Alexandre Duret-Lutz  <duret_g@epita.fr>
        * configure.ac: Check for getdefs, hevea, and texi2dvi.
        Don't check for texi2pdf and texi2html (unused).
        Use AC_CHECK_PROGS instead of AC_PATH_PROG.
        * doc/Makefile.am: Use the tools discovered by configure.

    prcs2git-id: 0_4.7

diff --git a/doc/configure b/doc/configure
--- a/doc/configure
+++ b/doc/configure
@@ -279,7 +279,7 @@ PACKAGE_STRING='olena-doc 0.4'
 PACKAGE_BUGREPORT='olena-bugs@lrde.epita.fr'
 
 ac_unique_file="ChangeLog"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS DVIPS TEXI2PDF TEXI2HTML INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS DVIPS TEXI2DVI GETDEFS HEVEA INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1205,38 +1205,35 @@ ac_config_sub="$SHELL $ac_aux_dir/config.sub"
 ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 
-# Extract the first word of "dvips", so it can be a program name with args.
-set dummy dvips; ac_word=$2
+for ac_prog in dvips
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_DVIPS+set}" = set; then
+if test "${ac_cv_prog_DVIPS+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $DVIPS in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_DVIPS="$DVIPS" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$DVIPS"; then
+  ac_cv_prog_DVIPS="$DVIPS" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_DVIPS="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_DVIPS="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_path_DVIPS" && ac_cv_path_DVIPS="$am_aux_dir/missing dvips"
-  ;;
-esac
 fi
-DVIPS=$ac_cv_path_DVIPS
-
+fi
+DVIPS=$ac_cv_prog_DVIPS
 if test -n "$DVIPS"; then
   echo "$as_me:$LINENO: result: $DVIPS" >&5
 echo "${ECHO_T}$DVIPS" >&6
@@ -1245,86 +1242,148 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-# Extract the first word of "texi2pdf", so it can be a program name with args.
-set dummy texi2pdf; ac_word=$2
+  test -n "$DVIPS" && break
+done
+test -n "$DVIPS" || DVIPS="$am_aux_dir/missing dvips"
+
+
+for ac_prog in texi2dvi
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_TEXI2PDF+set}" = set; then
+if test "${ac_cv_prog_TEXI2DVI+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $TEXI2PDF in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_TEXI2PDF="$TEXI2PDF" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$TEXI2DVI"; then
+  ac_cv_prog_TEXI2DVI="$TEXI2DVI" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_TEXI2PDF="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_TEXI2DVI="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_path_TEXI2PDF" && ac_cv_path_TEXI2PDF="$am_aux_dir/missing texi2pdf"
-  ;;
-esac
 fi
-TEXI2PDF=$ac_cv_path_TEXI2PDF
-
-if test -n "$TEXI2PDF"; then
-  echo "$as_me:$LINENO: result: $TEXI2PDF" >&5
-echo "${ECHO_T}$TEXI2PDF" >&6
+fi
+TEXI2DVI=$ac_cv_prog_TEXI2DVI
+if test -n "$TEXI2DVI"; then
+  echo "$as_me:$LINENO: result: $TEXI2DVI" >&5
+echo "${ECHO_T}$TEXI2DVI" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-# Extract the first word of "texi2html", so it can be a program name with args.
-set dummy texi2html; ac_word=$2
+  test -n "$TEXI2DVI" && break
+done
+
+if test -z "$TEXI2DVI"; then
+   { { echo "$as_me:$LINENO: error: texi2dvi not found -- please install Texinfo" >&5
+echo "$as_me: error: texi2dvi not found -- please install Texinfo" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+for ac_prog in getdefs
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_TEXI2HTML+set}" = set; then
+if test "${ac_cv_prog_GETDEFS+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $TEXI2HTML in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_TEXI2HTML="$TEXI2HTML" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$GETDEFS"; then
+  ac_cv_prog_GETDEFS="$GETDEFS" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_TEXI2HTML="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_GETDEFS="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_path_TEXI2HTML" && ac_cv_path_TEXI2HTML="$am_aux_dir/missing texi2html"
-  ;;
-esac
 fi
-TEXI2HTML=$ac_cv_path_TEXI2HTML
-
-if test -n "$TEXI2HTML"; then
-  echo "$as_me:$LINENO: result: $TEXI2HTML" >&5
-echo "${ECHO_T}$TEXI2HTML" >&6
+fi
+GETDEFS=$ac_cv_prog_GETDEFS
+if test -n "$GETDEFS"; then
+  echo "$as_me:$LINENO: result: $GETDEFS" >&5
+echo "${ECHO_T}$GETDEFS" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
+  test -n "$GETDEFS" && break
+done
+
+if test -z "$GETDEFS"; then
+   { { echo "$as_me:$LINENO: error: getdefs not found -- please install AutoGen" >&5
+echo "$as_me: error: getdefs not found -- please install AutoGen" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+for ac_prog in hevea
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_HEVEA+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$HEVEA"; then
+  ac_cv_prog_HEVEA="$HEVEA" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_HEVEA="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+HEVEA=$ac_cv_prog_HEVEA
+if test -n "$HEVEA"; then
+  echo "$as_me:$LINENO: result: $HEVEA" >&5
+echo "${ECHO_T}$HEVEA" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$HEVEA" && break
+done
+
+if test -z "$HEVEA"; then
+   { { echo "$as_me:$LINENO: error: hevea not found -- please install HeVeA" >&5
+echo "$as_me: error: hevea not found -- please install HeVeA" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 am__api_version="1.6"
 # Find a good install program.  We prefer a C program (faster),
@@ -2282,8 +2341,9 @@ s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@DVIPS@,$DVIPS,;t t
-s,@TEXI2PDF@,$TEXI2PDF,;t t
-s,@TEXI2HTML@,$TEXI2HTML,;t t
+s,@TEXI2DVI@,$TEXI2DVI,;t t
+s,@GETDEFS@,$GETDEFS,;t t
+s,@HEVEA@,$HEVEA,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
